parallaxinc/BlocklyProp

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
This adds a help link to the right of the view dropdown as requested by @PropGit in #125
> Add help link in editor menu

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
This PR adds the functionality to create a new project from a menu in the menubar. I believe this is necessary because the user should not always have to return to the BlocklyProp's homepage or go into an existing project to create a new project.
I will need to test this before it is merged into the master branch.
@PropGit What are your thoughts about this?
> Add 'New Project' menu to menu bar

- src/main/webapp/frame/framec.jsp
This PR adds some default blocks to other blocks. I think this is useful for the beginner because the new blocks give them a sense for an example of the configuration of the block. @PropGit what do you think?
> Add default math blocks

- src/main/webapp/cdn/blockly/generators/propc/sd_card.js
I forgot to fix these in the previous commit because the category wasn't visible when I did my evaluation.
> Fix quotes in SD card blocks

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
Ok here it goes...another try at fixing variable handling. Unlike my last attempt, this should not break BlocklyProp's ability to use variables.
This PR should allow you to now
1) Use all basic variable types (int, float, char, boolean)
2) Create char arrays (support for other arrays isn't in there yet)
> Another attempt to fix variable handling

- src/main/webapp/cdn/blockly/generators/propc.js
Note: This requires #281 to be merged before this.
Small background change to give developers the ability to create global variables (with respect to scope) without using BlocklyProp's built-in variable handling. This is required for a number of blocks.
> Add global variables

- src/main/webapp/cdn/blockly/generators/propc.js
This fixes what Mr. Martin brought to my attention this afternoon. Unfortunately, I believe it will only be possible to default these variables to integer type.
> Set all variables default to int if they are used undeclared

- src/main/webapp/cdn/blockly/generators/spin.js
The Spin reserved words for Integer and Boolean were misspelled. I did not see any errors related to this issue but went ahead and corrected the spelling.
> Replace misspelled keywords 'integer' and 'boolean'

- src/main/webapp/cdn/blockly/generators/propc/base.js
Correct compile error in issue #446, C, rc_time(), block
> Remove spurious ';\n' from output of rc_time component

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Created a text size block for the RGB OLED display as requested in issue #407
> Add OLED font size block.

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
These blocks return a number representing the maximum number of pixels available in the vertical or horizontal direction on the display.
> Add OLED blocks to return maximum display height and width

- src/main/webapp/cdn/blockly/generators/propc/oled.js
JavaScript was interpreting the 'width + height' as a string operation rather than a numeric operation.
> Correct implementation of formula to compute radius of rounded corners

- src/main/webapp/cdn/blockly/generators/propc/oled.js
The existing code produces a function call that is missing a comma between the fifth and sixth parameters. This patch corrects that omission.
> Correct missing comma in function call

- src/main/webapp/cdn/blockly/generators/propc/oled.js
When the value block is replaced with a max_height or a max_width block, the replacement blocks return a string that is a function call into the OLED library. The current code is trying to convert this to a number and failing with a NaN error. 
The new code will simple pass the values returned from the value or max_* blocks and let the C compiler work out the math.
> Update code to compute rectangle corner radius

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
I missed the main page "New Project" menu in my last PR, sorry.
> Change new spin project to S3 Robot project in main page menu

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Reference issue #586, create new blocks for OLED to set cursor position, write a string and write a number formatted in decimal, hexadecimal, octal or binary
> Additional OLED blocks

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Reference issue #586. The print number function accepts a float value and not a string value.
> Correct print number to accept only numeric input

- src/main/webapp/cdn/blockly/generators/propc/oled.js
Changed back to "colormath.h" - prompted because testing was done against a draft version of SimpleLibraries that used "colorMath.h" - Issue #601
> Changed colorMath back to colormath

- src/main/webapp/cdn/blockly/generators/spin.js
- src/main/webapp/cdn/blockly/generators/spin/scribbler.js
- src/main/webapp/cdn/blockly/generators/spin/serial.js
- src/main/webapp/cdn/blockly/language/common/math.js
- src/main/webapp/frame/framespin.jsp
- Added reserved words from Propeller Manual v1.2 appendix A
- Set Spin Propeller Activity Board WX baud rate to 9600, to work around Scribbler robot users possibly selecting it instead of the Scribbler robot
- Changed Scribbler 3 description from 'C3' to 'S3'
- Added Spin blocks for random numbers
- Reordered Scribbler drive block drop-down menu from straight.left,right to left,straight,right
- Added a stop servo block
- Changed product name styling from Ping and PING))) to Ping)))
- Separated Spin Boolean and integer constants from generic ones, and set colors to match the appropriate Spin menu color
- Added a Spin comment block
- Modified the servo blocks to automatically launch the Servo32 object
- Modified the serial and servo blocks to launch their respective objects from within …
> added Spin blicks for random number generation, uppdated other Spin blocks, added more reserved words for Spin

- src/main/webapp/cdn/blockly/language/common/pins.js
The mu symbol, by itself, is meaningless.
> Update block prompt pulse_out

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/frame/framec.jsp
Reference issue #666. Replace the Terminal move to x and move to y blocks with one block that uses x,y coordinates.
> Terminal Move to x,y block

- src/main/webapp/cdn/blockly/generators/propc/console.js
Terminal print number had the checkbox's result inverted
> Fixed an inverted conditional

- src/main/webapp/cdn/blockly/generators/propc/console.js
Fixed a missing escaped char, changed from \n to \r when "then a new line" box is checked for better compatibility with SimpleIDE.
> Fixed errors in Terminal Print blocks

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
The client files that are distributed from the BlocklyProp site have been updated. The .zip files are no longer distributed. Instead, installers are provided for Mac OS-X and Windows 64 bit. The updates in this PR address these changes in the UI.
> Update client download pages to reflect new client filenames

- src/main/webapp/cdn/blockly/language/common/pins.js
[ This is a PR with fixed merge conflict from MatzElectronics' #712 ]
Creates more condensed and safer EEPROM blocks - more detailed descriptions in the commits. Also re-hides i2c blocks - it may be some time before those get the attention they need to be used properly.
> Condensed EEPROM blocks (merge-fix for MatzElectronics)

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/monitoring/BlocklyPropInstrumentedFilterContextListener.java
- src/main/java/com/parallax/server/blocklyprop/monitoring/Monitor.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/cdn/blockly/generators/spin/scribbler.js
- src/main/webapp/frame/framespin.jsp
This update adds a S3 reset block to the Spin block family. The block reloads the S3 with the default demo program.
An application monitor is also included in this PR. It will allow us to monitor the app in real time to a console and/or to a Graphics server.
[Note that this change also requires an update to the blocklyprop.properties file.]
> S3 Reset Block - Application Monitoring

- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
A missing '/' results in a 404 error. Corrected.
> Add a missing forward-slash to a file URL

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/language/common/logic.js
- src/main/webapp/frame/framec.jsp
Creates "number" and "string" subcategories under "Control", adds string manipulation and comparison blocks.  Updates Terminal print to allow single char printing to terminal as well.
> Add string blocks

- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
Sometimes HTML and XML do not behave in the same way. Where a
would be legal XML, it is not acceptable HTML. Corrected the error with a
construct.
> Correct an ending DIV tag that was preventing proper OS detection.

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/language/common/pins.js
The block definitions had two tool tip function calls. The second, empty call obliterated the first tool tip call, destroying the tool tip message. Bahahhahaha
> Remove empty SetToolTip calls

- src/main/webapp/cdn/blockly/language/common/base.js
Issue #803 is corrected in this patch.
> Correct the spelling of the hertz abbreviation from 'hz' to 'Hz'

- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/utils.js
Unused return code appears to be an artifact from a previous refactor operation.
> Remove unsed return function. Remove newline string from code generator.

- src/main/webapp/cdn/blockly/generators/propc.js
Pin selection on the Propeller Activity Board WX is currently set to the range of 0-13. This patch extends the range to 0-17.
> Extend selectable pins from 13 to 17

- .gitignore
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
Opening an existing project that contains older, retired block names and geometry were not always being converted correctly when being loaded.
> Correct error handling in project retrieval code

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/DaoModule.java
- src/main/java/com/parallax/server/blocklyprop/config/PersistenceModule.java
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/UserDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/monitoring/Monitor.java
- src/main/java/com/parallax/server/blocklyprop/utils/HttpServletRequestImpl.java
- src/main/resources/logback.xml
- src/test/resources/logback-test.xml
Replaced log4j with logback. Updated the ProjectDaoImpl.java file to issue log events as a test run.
> Enable Application Logging

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
PropC projects were experiencing corrupt blocks when the project contained a math_integer block. The code that determines project type was calling the wrong transformation function when a project was loading. This has been corrected.
> PropC Blocks corrupted when loading project

- src/main/java/com/parallax/server/blocklyprop/jsp/Properties.java
- src/main/webapp/WEB-INF/properties.tld
- src/main/webapp/frame/framec.jsp
This update allows blocks of code in .jsp files to be enabled or disabled from a configuration file settings. This is done initially to disable blocks that have note been fully verified when an update is sent to production.
A new Boolean setting has been added to the blocklyprop.properties file:
experimental.menu = true
This setting will enable or disable code blocks in the framec.jsp file that are surrounded by specific JSTL tags.  If the property setting matches is set to true, the code between the <c:choose /> tags is included. Otherwise it is excluded. 
```
<c:choose>
<c:when test="${experimental == true}">
<category name="WX Module">
...
</category>
</c:when>
</c:choose>
```
> Configurable experimental code blocks

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Shouldn't need it - it was for array support when BlocklyProp was originally designed, but that's handled much differently now.
> Turn off legacy code that's causing variable typing issues

- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
The BlocklyProp client installer for MacOS is now a pkg file. Update the links to reference the new file type.
> Update client download pages for change in MacOS distribution

- pom.xml
Reference security issue [CVE-2016-6802](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6802)
Apache Shiro before 1.3.2 allows attackers to bypass intended servlet filters and gain access by leveraging use of a non-root servlet context path.
> Update Apache Shiro to 1.3.2 to address security issue CVE-2016-6802

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/security/BlocklyPropSessionDao.java
Update the pom.xml to use java 1.8.x in preparation for package updates that require java 1.8.
Set the session timeout to a hard one hour limit because the current default is three minutes.
> Move to java 1.8

- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/UserServiceImpl.java
The error occurs while retrieving the screen name associated with the owner of each project in the list. If the user record has been removed, the screen name is unavailable. The code assumes that the user record is always available. 
The larger question is why a user record can be removed while it still owns projects.
> Trap NullPointerException that occurs when listing current projects

- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmRequestServlet.java
Servers are reporting miscellaneous 500 errors. Add logging to clarify the nature of the error(s).
> Add logging to email confirmation processing

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
The BP editor is receiving an empty project file at seemingly random times. Adding logging in the relevant code to characterize the data.
> Add logging to track null project issue

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/frame/framec.jsp
Depreciates "simple" s3 blocks in the C system, replaces them with equivalent combinations of blocks, with one catch: blocks with statement inputs don't get transmogrified unless there is at least one block inside of the statement inputs.
As a result, old blocks are not disabled or changed.  Instead, they have been removed from the menus, and new blocks build for them to be transmogrified into.
Recommend setting a future calendar date and task to periodically check for any remaining use, and once a certain threshold (or zero) is reached, then delete them entirely.
> Depricate 'simple' S3 C blocks add replacements & transmogrifiers

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/cdn/blockly/toolboxfilter.js
- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/frame/framec.jsp
Initial addition of a "view in grayscale" feature #1039 - double wrapped, uses URL tag to activate
Bug fixes:
- bug related to variable renaming introduced by me forgetting to remove renaming handlers from a block that didn't contain variables.
- changed all "setTitleValue" to "setFieldValue" - setTitleValue is deprecated.
- bug in graphing modal where data on the graph wasn't properly cleared out and caused a re-opening of the graphing window to choke
- matched colors in the toolbox labels to the colors of the blocks (blocks were changed some time ago, but the toolbox menu didn't keep up)
- commented out now unused S3 C blocks #1026 
- re-add menu options to S3 is stalled block that were lost in the initial switchover
> Bug fixes: variables, graphing, add grayscale feature

- src/main/java/com/parallax/server/blocklyprop/services/impl/UserServiceImpl.java
The userDao object is not explicitly initialized in the constructor. It is used in a few class methods without verifying that it has been initialized. This triggers a NullPointerException. This patch verifies that the object reference is not null before using it.
> Add code to handle a possible uninitialized object

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/editor/blocklyc.jsp
Adds tooltips to buttons on graphing modal
improvements to generated series labels in graphing modal - prep to display live values
> Graphing improvements

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Reverse a previous commit to correct an issue where variable block names that contained a space character were no longer getting pre-processed to replace the space character with an underscore to allow the variable name to compile without error.
> Block variable names that contain one or more spaces

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Variable block names can contain space characters. This commit corrects an issue where the space characters in the variable name were not being replaced with underscore  ('_') characters, subsequently causing the project to fail to compile.
> Correct variable block naming

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Correct an issue where variable blocks where the variable name contains one or more space characters was not getting preprocessed to replace the space characters with underscore characters. This would cause the project to fail a compile.
> Variable blocks name with spaces

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/propterm.js
Changes auto-scroll on terminal.  Should now only auto-scroll when a '\r' or '\n' is received and the terminal is already at the bottom of the viewbox.
> Improve terminal scrolling, fix empty project error

- src/main/webapp/cdn/blockly/generators/propc/sensors.js
Fixed day, month, and year that were swapped around, added adjustments for dates that end up ahead or behind due to time-zone differences.
> Fix GPS date/time block

- src/main/webapp/cdn/blocklypropclient.js
Fixed another aspect causing autoconnect failures.  In this case, terminating BPL and restarting BPL swiftly, before the heartbeat notices the first connection was lost, caused the second BPL session to remain disconnected forever.
> Autoconnect Fix 2

- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/WEB-INF/servlet/index.jsp
HTML 5 pages should begin with a <!doctype html> attribute. That attribute was missing in the index.jsp page.
Add a basic framework for the MOTD feature referenced in #1154.
> Add missing doctype; Add MOTD placeholder

- pom.xml
Jenkins does not like to do code generation on missing tables.
> Disable Jooq code generation.

- src/main/resources/shiro.ini
Shiro's default session management does not work in a cluster environment. Shiro does have a cluster management server, but it is not implemented in this project. In it's place, the database will run a scheduled event to purge old sessions from the blocklyprop.sessions table.
> Disable session management.

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/blocklypropclient.js
Relaxed version limitation to cover all of v0.6.x.
> Set minimum allowed BP Client to v0.6.0.

- src/main/webapp/cdn/propterm.js
New version-sensitive code in a previous commit accidentally excluded it, making it global.
> Fixed echo filter to be version-sensitive.

- db-updates/0000-admin.sql
- db-updates/0001-initial.sql
- db-updates/0002-add_share-key.sql
- db-updates/0003-rich-text-editor.sql
- db-updates/0004-friends.sql
- db-updates/0005-fix_share-key_autoincrement.sql
Statements could be inadvertently executed against the wrong database.
> Refactor to include the database reference in the table DDL

- src/main/webapp/cdn/blocklyc.js
Reverted recent minEnc64Ver change back to minVer - accidental bug creation.
Now it will handle BP Clients v0.6.0+ properly.
> Reverted minVer change.

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/documents/confirm/confirmed.textile
Fixes issue #1351 
The link was missing a double quote character.
Bump up the build number.
> Correct issue with account confirmation textile file

- src/main/resources/documents/index.textile
- src/main/webapp/WEB-INF/includes/pageparts/footer.jsp
- src/main/webapp/WEB-INF/includes/pageparts/head/basic.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/html.jsp
- src/main/webapp/WEB-INF/servlet/index.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile-oauth.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
- src/main/webapp/WEB-INF/servlet/project/not-authorized.jsp
- src/main/webapp/WEB-INF/servlet/project/not-found.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-spin.jsp
- src/main/webapp/WEB-INF/servlet/public-profile.jsp
- src/main/webapp/WEB-INF/servlet/register/register.jsp
- src/main/webapp/WEB-INF/servlet/register/registered.jsp
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/projectcreate.jsp
Minor fixes to correct various HTML errors.
Replaced the Textile-driven home page splash image with the equivalent inline HTML code. The Textile version of the code was embedding and extra set of <html></html> tags in the document.
Added a <!DOCTYPE html> declaration to all the files that were creating html pages without a doctype definition.
> Miscellaneous updates to code

- src/main/webapp/editor/blocklyc.jsp
This is really weird. If the <!DOCTYPE html> is inserted at the top of the HTML document, the editor pallet renders to about 300 pixels tall. Remove the declaration, and the editor pallet goes back to normal dimensions. 
@MatzElectronics This file has a ton of potential HTML errors, mostly related to unknown attributes. I'm not sure if it's related, but something doesn't like HTML5 in this page.
> Remove DOCTYPE declaration to correct 300px high editor pallet.

- pom.xml
Adjust project file to exclude db schema build. Look for config file in project root.
> Backing off project file changes that are breaking Jenkins

- src/main/webapp/cdn/editor.js
- src/main/webapp/editor/blocklyc.jsp
Continuing to make HTML more valid.  Although the <!DOCTYPE html> tag is required, it appears to be incompatible with inline XML for some browsers.  Removing it and going back to doing some research to find the best way to support it.
> add 'data-' to XML block list names

- src/main/webapp/editor/blocklyc.jsp
Continuation of #1402, img tags that do not start with any content until filled with JS later in the page load need a dummy value for the src attribute. "//:0" does not generate an unnecessary server request.
> Add blank source to empty img src attributes

- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectSharingServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectLinkServlet.java
Improve logging messages for the shared project link code.
It appears to be possible to fail to create a shared project link within the dao layer. This code will at least detect the condition and report it back to the client.
> Add code to detect a failed project load

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectSharingDaoImpl.java
This will mirror the state of the UI when the user clicks on the checkbox to activate the link. If the shared project record does not exist, we create a new one. However, because the UI shows the box as checked, we need to default the new record to active as well.
> Set new shared project link records acive when created

- src/main/java/com/parallax/server/blocklyprop/db/dao/ProjectSharingDao.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectSharingDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/ProjectSharingService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectSharingServiceImpl.java
A project cannot be deleted until the related project sharing link records have been removed.  Updated the shared project code to actually delete the record rather than simply revoking the link. This avoids the foreign key constraint error when an attempt is made to delete a project.
Reference issue #1487
> Add code to remove project sharing records linked to project

- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
Removed an extraneous ',' in the method signature.
> Correct syntax error from last change to this file.

- src/main/java/com/parallax/server/blocklyprop/servlets/HelpServlet.java
The help system is getting deployed to the wrong target directory on the application server. Add logging to the help system initialization to identify the location where the help system expects to find the files.
> Add logging to help subsystem to diagnose a missing help system error.

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/utils/HelpFileInitializer.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/logback.xml
Update log config to use tomcat8 logging directory. 
Add support for dev and production build environments in pom.xml. 
Bump up build number to 0.100.439
> Updates for tomcat 8 support

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Someone, perhaps me, fat-fingered the version number on a prior commit. This patch corrects the error.
> Correct error in application version number in the 0.101 branch.

- pom.xml
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Correct an issue where the major and minor version number in the build was not matching the expected major/minor version number in the CI system. This caused the CI system to continue deploying the old 0.101 version to the Demo server.
Also removing unneeded dependencies in the application pom file.
> Update revision number to 1.0.440 to build Demo.

- src/main/java/com/parallax/server/blocklyprop/security/CloudSessionAuthenticationRealm.java
- src/main/java/com/parallax/server/blocklyprop/services/SecurityService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/resources/logback.xml
Reference issue #1445, add code to propagate the EmailNotConfirmed exception from the Cloud-Session server interface. Still need to update the UI to detect and enumerate this error.
Update logback config to use CatalinaHome/logs for logging.
> Add EmailNotConfirmed exception where appropriate.

- src/main/java/com/parallax/server/blocklyprop/servlets/PublicProfileServlet.java
All calls to cloudSessionUserService.getUser() must now handle the EmailNotConfirmed exception. This ensures that nothing happens in the system on behalf of an invalid (unconfirmed) account.
> Correct error introduced with the EmailNotConfirmed exception.

- src/main/webapp/editor/blocklyc.jsp
This is handled within jQuery's .ready() function instead.
> Remove redundant function call

- pom.xml
Jenkins is reporting this error:
```
16:04:11 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project BlocklyProp: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
```
Added the missing Surefire plugin to the project.
> Add surefire package now required by Jenkins CI.

- src/main/java/com/parallax/server/blocklyprop/rest/RestProfile.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProfileServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PublicProfileServlet.java
Add code to trap a new EmailNotConfirmed exception available from the Cloud Session server. This exception is generated when the user attempts to login or perform a password reset with an email address that has not yet been confirmed.
> Add code to trap new Cloud Session exception.

- pom.xml
One or more packages included in the project make use of the maven-surefire plugin for unit testing. The build process throws an error when unit testing is enabled:
```
The forked VM terminated without properly saying goodbye
```
The Apache Surefire FAQ says this about the error:
Surefire does not support tests or any referenced libraries calling System.exit() at any time. If they do so, they are incompatible with Surefire and you should probably file an issue with the library/vendor. Alternatively the forked VM could also have crashed for a number of reasons. Look for the classical "hs_err*" files indicating VM crashes or examine the Maven log output when the tests execute. Some "extraordinary" output from crashing processes may be dumped to the console/log. If this happens on a CI …
> Add surefire plugin configuration to disable testing.

- src/main/java/com/parallax/server/blocklyprop/servlets/TextileIndexServlet.java
This PR addresses issue #1556. Refactor code to trap the UnknownSessionException and return the client browser to the home page as an unauthenticated user.
> Correct session timeout stack dump

- pom.xml
- src/main/resources/logback.xml
Reconfigure the log configuration to roll the log files over at 10MB and store no more than 20 archive files.
> Rotate log files at 10MB

- src/main/java/com/parallax/server/blocklyprop/config/DaoModule.java
- src/main/java/com/parallax/server/blocklyprop/config/PersistenceModule.java
- src/main/java/com/parallax/server/blocklyprop/config/RestAPIVisualizeBootstrap.java
- src/main/java/com/parallax/server/blocklyprop/config/RestModule.java
- src/main/java/com/parallax/server/blocklyprop/config/ServiceModule.java
- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/jsp/GetCdnUrl.java
- src/main/java/com/parallax/server/blocklyprop/jsp/GetUrl.java
- src/main/java/com/parallax/server/blocklyprop/jsp/Properties.java
- src/main/java/com/parallax/server/blocklyprop/jsp/SetLocale.java
- src/main/java/com/parallax/server/blocklyprop/security/CloudSessionAuthenticationRealm.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/AuthenticationServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/AuthenticationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PingServlet.java
- src/main/resources/shiro.ini
- src/main/webapp/WEB-INF/includes/include.jsp
- src/main/webapp/WEB-INF/includes/pageparts/loginform.jsp
- src/main/webapp/WEB-INF/properties.tld
- src/main/webapp/WEB-INF/servlet/profile/profile-oauth.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
- src/main/webapp/WEB-INF/servlet/register/register.jsp
- src/main/webapp/WEB-INF/url.tld
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/login.jsp
- src/main/webapp/projectcreate.jsp
- src/main/webapp/projects.jsp
Added the MIT license head to more files.
Evaluated code with reference to issue #1583 and found that the Shiro package is likely performing a string trim() on the password contents prior to encrypting it for the password comparison.
> License headers and minor code refactoring

- pom.xml
Inadvertently left the properties file pointing to a test copy. This patch will correct the build process.
> Remove debugging artifact from the pom file

- pom.xml
- src/main/webapp/META-INF/context.xml
The production deployment will not start because something is requesting an old version of the logging library. We're not sure where that is coming from yet.
> 1.1 Update

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/monitoring/Monitor.java
- src/main/java/com/parallax/server/blocklyprop/utils/HelpFileInitializer.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/logback.xml
- src/main/webapp/editor/blocklyc.jsp
Address an issue where the production servers were unable to start the blockly application because of a missing LogManager() class. This class is being referenced by at least one support package and cannot be updated immediately due to other dependencies. 
Correct the logic in the help system loader to allow the module to report details when the help system source files are inaccessible. 
Update logging configuration file to remove unused settings.
Increment the build number from 446 to 447.
> 1.1 pre-deployment updates

- src/main/webapp/editor/blocklyc.jsp
Amazingly, this breaks a lot of code in the editor.
> Backing off DOCTYPE commit.

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
The internal help system has been a hot mess for some time now. This update replaces the link to the help system with a link to the Blockly resources located on the Learn site. The internal help system is deprecated and will be removed in a subsequent release.
> Replace home page help link with a refernece to the Learn web sites.

- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/servlets/HelpSearchServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/HelpServlet.java
- src/main/java/com/parallax/server/blocklyprop/utils/HelpFileInitializer.java
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/my/projects.jsp
#1638 The help link in the drop-down menu on the project editor page is currently pointing to a help system on the BP server that has been redirected to content on learn.parallax.com. 
This update corrects the anchor tag in the menu item to point to the help system located on the learn web site.
> Issue #1638 - Update Help URI to point to help system hosted on learn

- src/main/java/com/parallax/server/blocklyprop/db/dao/ProjectSharingDao.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectSharingDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/services/ProjectSharingService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectSharingServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/utils/RestProjectUtils.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
This update corrects a corner use case where a currently logged in user is viewing a private project that is accessed through a Shared Project link and the currently logged in use attempt to save the project into their own library. 
The expected behavior was for the server to create a new, private, unshared project in the currently logged in user's library. Instead, the Save and Save-As functions would silently fail and leave the user in the original private shared project. No new project was created.
> Address corner use case on issue #1500

- src/main/resources/shiro.ini
They are supposed to be authenticated.
> Corrected error in v2 REST API access level.

- src/main/java/com/parallax/server/blocklyprop/servlets/PublicProfileServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Corrects issue #1658. A NullPointerException can occur through a rare but possible chain of events. 
When a request is set to the Cloud Session server and the Cloud Session server is unable to contact the back end database, the Cloud Session server returns an empty user object, which is not a expected result in the BlocklyProp code.
Ultimately, the root cause will need to be addressed in the Cloud Server. This patch will operate as a defensive measure until that occurs.
> Correct Issue 1658

- src/main/java/com/parallax/server/blocklyprop/rest/RestCompile.java
- src/main/webapp/WEB-INF/servlet/index.jsp
Add MIME type to some JavaScript declarations where it was omitted. Without them, the browser may interpret the content as a plain text stream.
Add support for obtaining metadata from the compiler server to indicate the version of the library in use by the compiler. This data can be used to help the UI ensure that the back-end libraries can support the blocks available in the UI.
> Correct Javascript declarations and add support for library metadata.

- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
The non-static code was causing an exception at application startup when run under Tomcat 9.x
> Make log handle needs to be static for the class.

- pom.xml
Correct a missing dependency.
```
java.lang.NoClassDefFoundError: org/apache/log4j/LogManager
at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:94)
at com.parallax.server.blocklyprop.config.SetupConfig.<clinit>(SetupConfig.java:52)
[ ... ]
```
> Add missing Log4j dependency.
