- blockly/generators/propc/base.js
- blockly/generators/propc/cog.js
- blockly/generators/propc/pointers.js
- blockly/generators/propc/variables.js
- Added volatile option in variable declaration
- Added static option in variable declaration
- Added int option when declaring a pointer
- Changed Pin HIGH and LOW messages
- Updated cog function to incorporate these new features & give user
more flexibility
> Fixed cog_run issues & Assorted updates

- README.md
- blockly/generators/propc.js
- blockly/generators/propc/procedures.js
- blockly/generators/propc/servo.js
- Moved methods below the int main() method and added a declaration statement before int main()
- Added a basic outline of a roadmap
> Update method declaration & Add roadmap outline

- blockly/generators/propc/GPS.js
- blockly/generators/propc/I2C.js
- blockly/generators/propc/RFID.js
- blockly/generators/propc/TiltandAcceleration.js
- blockly/generators/propc/activitybot_library.js
- blockly/generators/propc/base.js
- blockly/generators/propc/eeprom.js
- blockly/generators/propc/pressure.js
- blockly/generators/propc/sd_card.js
- blockly/generators/propc/sensors.js
- blockly/generators/propc/servo.js
- blockly/generators/propc/wavplayer.js
- webcontent/framec.html
- Bug fixes. Every single one of my blocks is now tested and works.
- Major overhaul of the SD_Card blocks. I have updated all of the SD_Card blocks to make it easier for the user to use. In addition, I removed unused variables and updated inputs to variable inputs.
- Updated interface frame code to remove blocks that I removed from the SD_Card category
> Block Updates

- blockly/generators/propc/TiltandAcceleration.js
- blockly/generators/propc/abdrive.js
- blockly/generators/propc/activitybot_library.js
- webcontent/framec.html
- Fixed MMA7455 width problem
- Fixed missing block problem
> Miscellaneous block updates

- blockly/generators/propc/base.js
These blocks were not used in the final code. I think I just forgot to delete the code previously.
> Removed blocks

- src/main/webapp/cdn/blockly/language/common/base.js
- src/main/webapp/frame/framec.jsp
I am opening a PR because I cannot test this code locally and I would appreciate a review before it gets merged into the master branch.
This addresses Mr. Lindsay's comment about a default stack size parameter. The other comments regarding the structure of the cognew block are not addressed in this PR.
> Fix Cognew stacksize parameter

- src/main/webapp/cdn/blockly/generators/propc/base.js
And fix my incorrect whitespace in the block.
> Add default text to string block

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp
> Enhance project details page

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
Fixes #137 
- Adds OFF option to Hackable Electronic Badge block
- Fixes related style issues
> Add OFF option to HEB RGB block

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
> Sync HEB touchpad & led numbering

- src/main/webapp/cdn/blockly/generators/propc/console.js
This fixes the error with the console variable printing block that Mr. Gracey identified
> Fix console_print_variables block

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/language/common/pins.js
- src/main/webapp/frame/framec.jsp
A few points that need to be addressed with this:
1) The value-input should be pre-filled, but I am not sure what value should be placed there. @cbradyatinquire @PropGit Do you guys have any input here?
> Add pulse in and pulse out blocks

- src/main/webapp/cdn/blockly/generators/propc/wav.js
- src/main/webapp/frame/framec.jsp
This PR adds support for WAV playing in C.
@PropGit Where can I find the documentation for the Spin language and the functions available?
> Add blocks for WAV

- src/main/webapp/cdn/blockly/generators/propc/TiltandAcceleration.js
- src/main/webapp/frame/framec.jsp
This PR fixes the blocks, makes a few changes, and adds them back into the C frame
> Fix support for tilt and acceleration blocks

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
> Fix HEB IR Receive block

- src/main/webapp/cdn/blockly/generators/spin.js
- Fix tabbing of new methods
- Remove imports (possible C code leftover)
> Fix a few spin generator issues

- src/main/webapp/cdn/blockly/generators/propc/sd_card.js
- src/main/webapp/frame/framec.jsp
This is just an initial round of SD Card blocks that will allow testing of some functions. I believe in the future this will have to be rewritten, but I need some input on what the final system for SD Card blocks should look like.
> Add initial version of SD Card blocks

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/frame/framec.jsp
> Add new Data Types subcategory

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- Variable name was incorrect, throwing an error and causing the block to not work
- Changed the structure of the block to reflect the changes requested in #147
> Correct issues with IR recieve block

- src/main/webapp/cdn/blockly/generators/propc/GPS.js
- src/main/webapp/cdn/blockly/generators/propc/TiltandAcceleration.js
- src/main/webapp/cdn/blockly/generators/propc/abdrive.js
- src/main/webapp/cdn/blockly/generators/propc/abvolts.js
- src/main/webapp/cdn/blockly/generators/propc/activitybot.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/bit_math.js
- src/main/webapp/cdn/blockly/generators/propc/cog.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/eeprom.js
- src/main/webapp/cdn/blockly/generators/propc/file.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/i2c.js
- src/main/webapp/cdn/blockly/generators/propc/joystick.js
- src/main/webapp/cdn/blockly/generators/propc/logic.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/generators/propc/pointers.js
- src/main/webapp/cdn/blockly/generators/propc/pressure.js
- src/main/webapp/cdn/blockly/generators/propc/procedures.js
- src/main/webapp/cdn/blockly/generators/propc/rfid.js
- src/main/webapp/cdn/blockly/generators/propc/sd_card.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/cdn/blockly/generators/propc/tv_remote.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/cdn/blockly/generators/propc/wav.js
This PR does a lot of cleaning on the C blocks in an attempt to:
1) fix a few miscellaneous issues (particularly with output types)
2) "standardize" the look of block code
Fixing item 2 makes it a lot easier to maintain the blocks (and make changes) because they all look similar.
> Do a lot of cleaning on C blocks

- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/i2c.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/cdn/blockly/quotes.js
- src/main/webapp/frame/framec.jsp
> Correct quotes issue

- src/main/webapp/cdn/blockly/language/common/pins.js
I figured out the issue with the Freqout block was caused by a few errors in the pulse_in & pulse_out blocks. These errors have been fixed in this PR.
> Fix timing category

- src/main/webapp/cdn/blockly/generators/propc/cog.js
- src/main/webapp/frame/framec.jsp
This PR redesigns the cog_new block to work with the new cog_end block.
Please note, this is a fairly major change to the cog_new block and it might require numerous redesigns. @PropGit What do you think of this new design?
> Redo cog_new & add cog_end block

- src/main/webapp/cdn/blockly/generators/propc/GPS.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/joystick.js
I believe I have fixed all extra spacing in the generated C code.
> Make generated code spacing consistent

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
After doing the redesign I forgot to change the generated code.
> Another attempt to fix generated HEB IR receive block code

- src/main/webapp/cdn/blockly/generators/propc/i2c.js
Turns out I just made a mistake when fixing the quotes issue.
> Fix broken protocols category

- src/main/webapp/cdn/blockly/generators/propc/TiltandAcceleration.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
This PR addresses 2 issues:
1) Currently broken HMC5883 category
2) IR Block issues ( @michel-cf can you confirm this fixes #181 ? I'm not 100% sure what is causing the issue... )
> Block fixes

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
This PR should help fix some of the variable issues we have been having with Blockly up until this point. I have added support for booleans, floats, and chars but have not implemented arrays yet. Before I add arrays, my changes should be thoroughly tested to determine whether this is a good fix. @michel-cf Do you think this is a good solution?
> Redesign variable handling & clean PropC generator

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/cog.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/eeprom.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/language/common/math.js
- src/main/webapp/frame/framec.jsp
- src/main/webapp/frame/framespin.jsp
- Fixes #250 
- Fixes #249 
- Fixes #246 
- Fixes #241 
- Fixes #229
> Issue fixes

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/joystick.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
This PR addresses most of the bugs that I created in the last 2 PRs (Variable handling fix and more issue fixes).
- Fixes #270 
- Fixes #269 
- Fixes #268 
- Fixes #267 
- Fixes #265 
- Fixes #264 
- Fixes #263 
- Fixes #262 
- Fixes #261 
- Fixes #260 
- Fixes #258 
- Fixes #271
> Today's issue fixes

- src/main/webapp/cdn/blockly/generators/propc/servo.js
> Add angle field for standard servo block

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/lib/beautify.js
- src/main/webapp/demo/blocklyc.jsp
- src/main/webapp/editor/blocklyc.jsp
C code formatter that fixes #289 (curly braces on new line)
> C code formatter

- README.md
- Grammatical fixes
- Remove outdated compatibility list
> Clean up main project README

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
Since I got my VM fully setup (thank you @PropGit @zfi !), I was able to start really messing with the BlocklyProp code and I fixed (and simplified) the variable changing process.
> Final variable fix; all should be well now

- src/main/webapp/cdn/blockly/generators/propc.js
I need this to make changes for a number of blocks.
> Add global (scope wise, not core wise) variables

- README.md
- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/lib/beautify.js
- src/main/webapp/demo/blocklyc.jsp
- src/main/webapp/editor/blocklyc.jsp
Note: This relies on other commits to be pushed to master before it can be merged
> Code formatter

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/rfid.js
- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/cdn/blockly/generators/propc/wav.js
- src/main/webapp/cdn/blockly/language/common/math.js
- src/main/webapp/frame/framec.jsp
This is another big PR and fixes many of the remaining issues, including
- #341 
- #334 
- #333 
- #314 
- #313 
- #382
> General fixes track demo

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/includes/pageparts/loginform.jsp
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/WEB-INF/includes/pageparts/project-login-dialog.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
- src/main/webapp/cdn/style.css
- src/main/webapp/login.jsp
- Latest projects
- Client download adds links for installers
- Show the reset password and email confirm link without the need for a failed login
- Hide public profile (still accessible from within project table)
> Layout improvements

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/cdn/blockly/generators/propc/wav.js
- src/main/webapp/frame/framec.jsp
> Fix a few more issues

- src/main/java/com/parallax/server/blocklyprop/servlets/TextileChangeLogServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/TextileClientDownloadServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/TextileClientInstructionsServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/TextileIndexServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/TextileLibrariesServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/TextileLicenseServlet.java
- src/main/java/com/parallax/server/blocklyprop/utils/ServletUtils.java
- src/main/java/com/parallax/server/blocklyprop/utils/TextileReader.java
Work around problem with demo server
> Work around https issue on demo server

- src/main/webapp/cdn/blockly/generators/propc/rfid.js
Updated the text on the block face as requested.
Swapped the parameters of the rfid_open() function call.
Tested OK in dev environment.
> Ref #436 - Changed block text. Correct swapped function parameters.

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Created the OLED Clear Screen block.
Reordered the parameters in the OLED initialization block per MattM request.
Verified that the generated code works when used in SimpleIDE.
> 423 rgb oled clear screen - issue #376

- src/main/webapp/cdn/blockly/colorPalette.js
Per Ken -
This is a proposed change of the color palette (again, sorry...) to increase the color space between each type of block to make them visually easier to differentiate.
> Update block colors

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Added code to support drawing a triangle and optionally filling the triangle.
> Add code to display a triangle line drawing or a triangle fill

- src/main/webapp/cdn/blockly/generators/propc/serial.js
Swapped Do and DI labels on the block. Note that the label no longer matches the pin names
> Issue 454 - Swap the display label for pins DI and DO.

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Add code to draw rectangles with or without rounded corners, with or without fill.
> Patch for issue #401 RGB OLED: Draw Triangle

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Add code to draw a circle with or without fill. Tested good on dev workstation.
> Ref issue #398 RGB OLED Circle

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Add OLED font color block. Tested good on local dev system.
> Add OLED font foreground and background color block

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Completed block for issue #422: RGB OLED: Font Loader
> Add OLED font loader block

- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-spin.jsp
- src/main/webapp/cdn/lib/xterm.js
- src/main/webapp/cdn/style-editor.css
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/editor/blocklyspin.jsp
- scrolling
- ascii 2: [x,y]
- carriage return included in newline
> Improve serial terminal

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp
- src/main/webapp/cdn/project.js
> Change confirm project delete based on sharing and fix project delete when shared

- blocklyprop-schema.sql
Update database schema to reflect current database state.
> Update database schema document

- src/main/webapp/cdn/blockly/generators/propc/xbee.js
Issue #454 is requesting a code change to match the change to the block labeling.
> Swapped dropdown defaults

- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/frame/framespin.jsp
A failed merge was committed - not sure how that happened yet.
> Correct files corrupted during last commit

- src/main/webapp/cdn/blockly/generators/propc/servo.js
Update servo block to provide user feedback if the angle selected was not within the range of zero to 180 degrees. Additionally, the generated code will ensure that the value falls within the range.
> Update servo to perform range checking

- src/main/webapp/frame/framec.jsp
Comment out the memory-related blocks while development continues on them.
> Hiding memory-related blocks

- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/frame/framec.jsp
Added missing prompt for angle.
Added a default value block for the angle.
> Add missing prompt to block

- src/main/webapp/cdn/blockly/language/common/base.js
Replacing the default drop-down list of pins with a custom list containing the numbers 0-15.
> Replace default pin list with fixed list of zero through 15

- src/main/webapp/cdn/blockly/language/common/procedures.js
Remove function block that returns a value.
> Remove base code to create a function call block with a return value

- src/main/webapp/cdn/blockly/generators/propc/abvolts.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/language/common/logic.js
- src/main/webapp/cdn/blockly/language/common/math.js
- Fix the value problem in #502 
- Correct the block colors within the "Values" category
> Other fixes

- src/main/webapp/frame/framec.jsp
Reorder OLED blocks to group text and geometry blocks together such that the text rendering blocks are grouped together and the geometry blocks are also grouped together.
> Remove duplicate menu items.

- src/main/webapp/cdn/blockly/generators/propc/TiltandAcceleration.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/cdn/blockly/generators/spin/math.js
- src/main/webapp/cdn/blockly/language/common/control.js
- src/main/webapp/frame/framec.jsp
Fixes:
- #497 
- #496 
- #465 
- #459 
- #557 
- #543 
- #495
> General fixes

- src/main/webapp/cdn/blockly/generators/propc/oled.js
Update the OLED drawing blocks to change the orientation from a wide, horizontal layout to a more compacts vertical layout.
> OLED drawing blocks reorientation

- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/frame/framec.jsp
> Create simple return control block

- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/frame/framec.jsp
Fixes #561 however it is contingent on https://github.com/parallaxinc/Simple-Libraries/issues/29 before it will work
> Add new ColorPal get colors block and rename the old one

- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/frame/framec.jsp
Fixes #574 , #575 , #576 , #577
> Terminal blocks

- src/main/webapp/cdn/blockly/generators/propc/tv_remote.js
Reference issue #546, changed the text on the block as requested.
> Update text on the Sony remote block

- src/main/webapp/cdn/blockly/language/common/procedures.js
This PR is in reference to issue #536. Removing the gear from the block.
> Remove mutator [the gear in the upper right corner] from function block

- src/main/webapp/cdn/blockly/generators/propc/console.js
> Clean up terminal printing blocks

- src/main/webapp/cdn/blockly/generators/propc/oled.js
Reference issue #579 to add a font drop down selector to the text_size block. Also refactored a switch statement.
> Add Font Selector in OLED Text block

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/frame/framec.jsp
There were a number of issues and this PR should fix all of them.
Do not merge yet because the functions that these blocks rely on are not in SimpleLibraries yet and the code might need to change...
> Fix issues with color blocks - WIP

- CONFIGURATION.md
- src/main/resources/shiro.ini
Disable session purge in multi-host environment. Correct error in port number
> Minor housekeeping corrections

- src/main/resources/shiro.ini
Did not correctly comment out the securityManager assignment line. This caused the app to fail.
> Missed commenting a line related to the scheduler

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/blocklyspin.js
- src/main/webapp/cdn/lib/xterm.js
Should fix quite a few errors with the serial terminal. Which exactly will need to be evaluated after merge.
- #523 should be ok
- #524 should be improved, but not completely fixed
- #570 should be ok
- #571 should be ok
- #572 should be ok
- #525 might have been fixed
- #523 should be ok
> Fixes quite a few of the serial terminal problem.

- src/main/webapp/cdn/lib/xterm.js
> Have carriage return include line feed instead of the opposite

- src/main/webapp/cdn/blockly/generators/propc/oled.js
Reference issue #601. The return value for the color picker has changed. Refactor all OLED blocks that manage color to work properly with new return value.
> Recode color handling in OLED blocks

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Corrected block prompts; added missing text block.
> 586 - OLED print text and print number block corrections

- src/main/webapp/cdn/blockly/generators/propc/oled.js
> Fix OLED blocks

- src/main/webapp/cdn/blockly/generators/propc/console.js
Changes that make the new terminal blocks invoke the serial terminal per #605.
NOTE: UNTESTED - I don't have a dev environment to test these!
> Update to new terminal blocks

- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/frame/framec.jsp
Matt coded this and @zfi provided minor update.
> Correct rounded rectangle issue - MMatz

- src/main/webapp/cdn/blockly/generators/propc/control.js
As requested by @mrodriguez-parallax in #465
> Fix control operator for for-loop

- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
Should fix all problems with the save-as feature. #433
> Fix save as feature

- src/main/webapp/cdn/blockly/generators/propc/oled.js
Simplified the output to use the function as it was designed :)
> Updated rectangle rounding generator

- src/main/webapp/cdn/blockly/generators/propc/sensors.js
Not in an issue - block wasn't tested - caught this one when I tried to test it.
> ColorPal block missing setup and includes

- src/main/webapp/WEB-INF/includes/pageparts/footer.jsp
Adding a string version number. Eventually this will be driven from the build environment.
> Add app version to home page

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations_nl.properties
- src/main/webapp/WEB-INF/includes/pageparts/footer.jsp
Update translation files to include app version information. Update page footer to display version number
> Place app version number on home page footer

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/frame/framec.jsp
Added a bunch of functionality to this block, removed clear screen block because of duplicate functionality within command block.
> LCD command block update

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
> Fixed a bug in Serial LCD command block

- src/main/webapp/cdn/blockly/language/common/pins.js
- src/main/webapp/frame/framec.jsp
> Correct prompt text and added default value block

- src/main/webapp/cdn/blockly/language/common/pins.js
- src/main/webapp/frame/framec.jsp
Reverts parallaxinc/BlocklyProp#648
> Revert "Correct prompt text and added default value block"

- src/main/webapp/cdn/blockly/generators/propc/abvolts.js
Thou shall not edit code without an IDE.
> Corrected syntax error in ab_volt_in Block

- src/main/webapp/WEB-INF/servlet/help/menu.jsp
- src/main/webapp/cdn/blockly/generators/propc/base.js
Hiding the help menu items until the help documents are complete
> Hide menu until help content is ready

- src/main/webapp/cdn/blockly/generators/propc/console.js
> Serial terminal update to use new library macros

- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/frame/framec.jsp
> Update terminal print with formating options

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/frame/framec.jsp
Reference issue #664 - Terminal print changes.
> Update block to include a default string block

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
Adding a pause before clearing the terminal.
> updated clear screen code per MM

- src/main/webapp/cdn/blockly/generators/propc/console.js
> Swap the row and column parms to column and row

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations_nl.properties
Update the version and build numbers.
> Public release #1

- src/main/webapp/cdn/blockly/generators/propc/oled.js
> Remove comma from last array element

- src/main/webapp/cdn/blockly/generators/propc/oled.js
> Hot Patch #1

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/frame/framec.jsp
Improved and added functionality to the serial LCD blocks
> Serial LCD block improvements

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/i2c.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/frame/framec.jsp
also, better error handling in i2c blocks, fixed layout of LCD init block.
> Improvements to serial protocol blocks

- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
Accidentally invoked the serial terminal
> Fix LCD print number

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/frame/framec.jsp
Repaired OLED circle block, fixed serial comm blocks, added string length block, standardized labeling on some (not all) HEB blocks.  Addresses #696, #695, and #693.
> Repairs and improvments

- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/oled.js
> Updates to print blocks

- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/debug_LCD.js
- src/main/webapp/cdn/blockly/generators/propc/eeprom.js
- src/main/webapp/cdn/blockly/generators/propc/i2c.js
- src/main/webapp/cdn/blockly/generators/propc/joystick.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/frame/framec.jsp
Hid SD card blocks (not finished/functional)
EEPROM blocks have improved addressing
Joystick blocks have improved PIN labels
Terminal, Serial, and EEPROM blocks select variable to store in by dropdown
Serial LCD cursor positioning (#683)
> Block label and behavior improvements

- src/main/webapp/cdn/blockly/generators/propc/TiltandAcceleration.js
- src/main/webapp/cdn/blockly/generators/propc/abvolts.js
- src/main/webapp/cdn/blockly/generators/propc/console.js
- src/main/webapp/cdn/blockly/generators/propc/eeprom.js
- src/main/webapp/cdn/blockly/generators/propc/math.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/serial.js
- src/main/webapp/cdn/blockly/generators/propc/wav.js
- src/main/webapp/cdn/blockly/language/common/math.js
- src/main/webapp/frame/framec.jsp
More fixes for improved consistency...
> Block labelling and appearance improvements

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
Issue #746. There is still a small CSS issue that is forcing a line wrap on the long label names.
> Updated download links with new file nemaes and new labels

- src/main/webapp/WEB-INF/includes/pageparts/head/basic.jsp
- src/main/webapp/WEB-INF/servlet/index.jsp
This looks good on the dev system. Let's see it on Demo.
> Implement a favicon for the site

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Update the New Project drop-down menu.
> Change new project S3 Scribbler with just Scribbler

- src/main/webapp/WEB-INF/includes/pageparts/head/basic.jsp
- src/main/webapp/WEB-INF/servlet/index.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile-oauth.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-spin.jsp
- src/main/webapp/demo/blocklyc.jsp
- src/main/webapp/demo/blocklyspin.jsp
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/editor/blocklyspin.jsp
- src/main/webapp/my/projects.jsp
- src/main/webapp/projectcreate.jsp
- src/main/webapp/projects.jsp
Add favicon to all files that generate full pages.
> Add Favicon to all files that generate full pages

- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/cdn/blockly/generators/propc/xbee.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
Tooltip text for AB-blocks
XBee block string terminators changed to ASCII-13 to encourage better behavior
Removed javascript alert in Std. Servo block
> Tooltips and a couple-o'-fixes

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/servo.js
- src/main/webapp/cdn/blockly/language/common/pins.js
fixes to servo_speed and set_pins blocks.  Set_pins is now "safer", and servo_speed was passing a value correctly.
> Improvements and fixes

- db-updates/0006-add-user-coach.sql
- src/main/webapp/cdn/blockly/generators/spin/variables.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
Add S3 tool tips originally provided from @MatzElectronics fork. 
The db update is unrelated to the S3 updates. It will be used in a subsequent update to provide a coach email address during registration.
> S3 Tool tips

- src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js
- src/main/webapp/cdn/blockly/generators/propc/rfid.js
Pushing updates submitted by @MatzElectronics
> Updates from MMatz

- src/main/webapp/cdn/blockly/generators/propc/xbee.js
Correct errors in the XBee C block.
> Updates provided by MMatz

- src/main/webapp/cdn/blockly/generators/propc/xbee.js
One more set of updates posted in email this morning.
> One more change set from MMatz

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Updating version stamp prior to release.
> Update app version to 0.93 build 251

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
> Testing post master merge

- src/main/webapp/WEB-INF/includes/pageparts/projecttable.jsp
As requested in #707 I have disabled the search function for Community Projects.
> Disable search in community projects

- pom.xml
- src/main/config/default/log4j.xml
Update the .pom file to use newer versions of log4j components. Update log4j default configuration file.
> Update log4j Settings

- src/main/webapp/cdn/blockly/generators/spin/scribbler.js
- src/main/webapp/frame/framespin.jsp
Adds a block to move the Scribbler robot to a position at an X and Y offset
Adds a block for an analog input from the Scribbler robot hacker port
Adds a block for a digital input from the Scribbler robot hacker port
> Add Scribbler blocks for move by X Y and analog and digital input blocks

- src/main/webapp/cdn/blockly/generators/propc/abdrive.js
- src/main/webapp/cdn/blockly/generators/propc/activitybot.js
- src/main/webapp/cdn/blockly/generators/propc/oled.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/frame/framec.jsp
Improvements to robot blocks and the OLED command block
> Update robot blocks

- src/main/webapp/cdn/blockly/generators/spin/control.js
- src/main/webapp/cdn/blockly/generators/spin/logic.js
- src/main/webapp/cdn/blockly/language/common/control.js
- src/main/webapp/cdn/blockly/language/common/logic.js
- src/main/webapp/frame/framespin.jsp
Separated Spin if, negate, integer compare, and logic compare from common code, to restore Boolean functionality
> Fix regression error in boolean Scribbler blocks.

- src/main/webapp/frame/framec.jsp
Updated the order of items in the Communicate and Sensor sub-menus to sort in alpha order.
> Issue #812 Menu order

- src/main/webapp/cdn/blockly/generators/propc/abdrive.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/frame/framec.jsp
Fixed drive distance block (removed an extra parenthesis)
Fixed display activitybot calibration block (wasn't calling terminal)
Improved ramping constants
Added drive stop block
> abdrive Block fixes

- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
Forgot to enclose the s3.h in double-quotes in all of the s3 propc blocks.
> Fixed calls to s3 c library

- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/frame/framec.jsp
Minor changes to clean up menus, error from previous commit, and s3 wait blocks.
> s3 block cleanup

- pom.xml
- src/test/java/com/parallax/blocklyprop/test/SandTest.java
Updated the pom.xml file to add support for junit unit testing.
Created an initial test package to exercise the DateConversion utility class.
Note: 
The build process will fail from this point forward if any of the unit tests fail. You have been warned.
> Initial configuration and build of unit testing.

- src/test/java/com/parallax/blocklyprop/test/SandTest.java
Separated the setup code from the actual test to make the process more readable.
> Refactor code to make the tests more readable.

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/frame/framec.jsp
- src/main/webapp/projectcreate.jsp
> Add advanced math and string blocks, "Flip" board type

- src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp
- src/main/webapp/WEB-INF/includes/pageparts/projecttable.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/cdn/blockly/generators/propc/s3.js
> Add "Flip" board type, change "Console" to "Terminal"

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/spin/serial.js
Also includes a fix to serial LCD commands
> Fixes to text printing - escaping % char

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp
- src/main/webapp/cdn/project.js
- src/main/webapp/editor/blocklyc.jsp
Attempts to address #627, #805, #846
> UI fixes and improvements

- src/main/java/com/parallax/server/blocklyprop/db/dao/ProjectDao.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
Updated the project dbo layer to update the 'last-change-date' field of the project table whenever a project description, the project canvas or whenever the project is cloned.
> Add timestamp to project updates and cloning operations.

- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectCreationServlet.java
Create a project sometimes throws an Invalid projecttype error. Reference issue #852
> Update error messages to differentiate between two failure modes

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/frame/framec.jsp
Addresses #856, #855, #854, #849, #844 
Partially Addresses #824
> Block addition, fixes, improvements

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/webapp/cdn/blockly/generators/propc/base.js
Prevents project breakage due to new block names.
> Alters user code on the fly

- src/main/webapp/cdn/lib/xterm.css
- src/main/webapp/cdn/lib/xterm.js
Attempts to fix extended-ascii char display (#524) and line-wrapping (#523, #632).
> Prevent line wrapping in terminal

- src/main/webapp/cdn/blockly/generators/propc/s3.js
Missing semicolons after simpleterm_reopen calls
> Add missing semicolons

- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PingServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/cdn/demoeditor.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/utils.js
- src/main/webapp/editor/blocklyc.jsp
This will add upload/download functions and UI elements to the system.
> Add upload/download (local file) functionality

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/footer.jsp
Replace the footer text with new variables. The build system will find and replace the build number for each build.
> Embed application and build numbers into the internationalization file

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/spin/scribbler.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/style-editor.css
- src/main/webapp/cdn/utils.js
- src/main/webapp/editor/blocklyspin.jsp
- src/main/webapp/frame/framec.jsp
> Minor fixes

- src/main/webapp/cdn/editor.js
@mrodriguez-parallax noticed an issue with the upload feature - again it has to do with the possibility of a user not saving their work before trying to upload and effectively wiping out their work.  Now, it will prompt you to save before you are allowed to upload.
> Prompt to save before upload

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Preparing to push to production.
> Demo version update

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/frame/framec.jsp
Allows for improved connection handling and monitoring with the Simple WX page.
> WX block improvements

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PingServlet.java
- src/main/webapp/WEB-INF/web.xml
Starting the process to add or update the source code and configuration file documentation.
> Add inline documentation

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/spin/scribbler.js
- src/main/webapp/cdn/editor.js
Turns off the "Load to RAM" button when using the s3 in the C editor
> s3 C UI improvements

- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/jsp/Properties.java
- src/main/resources/application.properties
- src/main/webapp/WEB-INF/properties.tld
Add settings in the blocklyprop.properties file to support offline operations. This is step one.
> Add support for offline mode in config file

- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/blocklyspin.js
> IMU block improvements, Remove COM3/COM4 from menu when disconnected

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/frame/framec.jsp
Also:
adds some older browser compatibility for JS functions used in array blocks
gives array blocks their own menu
> Array and HEB block fixes

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Plus makes "array" lowercase in block title for consistency.
> Fix for illegal chars in array names

- src/main/webapp/frame/framec.jsp
Also ran a code "format" to clean up code appearance.
> Activate Fingerprint blocks

- src/main/webapp/cdn/blockly/generators/propc/control.js
> For-loop block fix

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
GPS blocks, repeat (for) stepping condition when variables are used to define parameters.
> Minor block repairs

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/frame/framec.jsp
Enables the new number block with a slider and range/allowed value detection.  Begins adding some ranges to blocks (many more to come there), removes some experimental text on robot blocks, moves "other"-only system blocks to the end of the block menu and gives them a less-ugly color.
> New fancy number block, system block color and menu improvements

- src/main/webapp/cdn/blockly/generators/propc/base.js
This fixes a error generated by a possible number condition that I missed during the initial testing of the block.
> Number block fix

- src/main/webapp/WEB-INF/includes/pageparts/language-switcher.jsp
- src/main/webapp/cdn/blockly/generators/propc/base.js
This fixes another error generated by a possible null condition that I missed during the initial testing of the block.
> Another bug fix

- src/main/webapp/cdn/blockly/generators/propc/base.js
Another variable that is somehow null under certain conditions.
> Another bug fix, part deux

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
Beginning the process of adding specified ranges to the blocks for the fancy number block to pick up and show the user if they are entering out-of-range values.
> Add set ranges to blocks

- src/main/webapp/cdn/blocklyc.js
> add Force-refresh instructions to alert boxes

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Preparing for another release.
> Setting release version 0.96.358

- blocklyprop.properties.example
- src/main/java/com/parallax/server/blocklyprop/jsp/Properties.java
Also add comments to code to improve documentation of the experimental menu feature.
> Add missing configuration option in example properties file

- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/spin/serial.js
- src/main/webapp/frame/framespin.jsp
Accidentally introduced underscores when copying code over from the SPIN version of the block.
> S3 block fixes and improvements

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/procedures.js
- src/main/webapp/editor/blocklyspin.jsp
- src/main/webapp/frame/framec.jsp
Fixes "Modal title" and a changed from "Console" to "Terminal" that was previously missed.
Better arrangement of C code generation order (safer for interdependent functions and easier to comprehend).
> S3 SPIN UI fixes and C code gen improvements

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/ServiceModule.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/SessionDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/db/utils/DataSourceSetup.java
- src/main/java/com/parallax/server/blocklyprop/security/BlocklyPropSessionDao.java
- src/main/java/com/parallax/server/blocklyprop/security/DataSourceProvider.java
- src/main/java/com/parallax/server/blocklyprop/services/SecurityService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/AuthenticationServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SessionServiceImpl.java
- src/test/java/com/parallax/blocklyprop/test/DataConversionTest.java
Refactored session management code and included javadoc structure that were missing.
Update POM to upgrade JOOQ from 3.6.1 to 3.6.4. Latest release is 3.9.1 but recommends Java 8.
Replace a number of print statements with proper logging.
Discovered a missing configuration option in the source for detailed session diagnostics.
Renamed test class to conform to proper naming conventions.
> Update session management

- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
Fixed error in repeat (for) block that resulted in no code generated when step size = +/- 1.
Improvements to s3 C motor and play polyphony blocks including range warnings.
Improvement to spin_integer block (for s3 C) giving it range warning capability.
> Repeat (for) block fix, s3 C block improvements incl. ranging)

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/security/BlocklyPropSessionDao.java
Refactor code in sessionDao to show new session ID in log file.
> Fix error in POM that caused build to fail. 

- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/servlets/SessionStateServlet.java
- src/main/resources/shiro.ini
There are a number of HTTP 500 events being logged when project code is updating.  It's possible that the sessions are timing out prior to the save.
Refactored the REST endpoint code for readability and included event logging for the project API.
Add framework to support the ability to monitor session metrics.
> Project REST API Update, New REST endpoint for session metrics

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blocklypropclient.js
- src/main/webapp/frame/framec.jsp
Improved user defined block
Improved BPC version detection/handling
S3 PROPC menu and block cleanup
Proper "experimental" wrapping where appropriate
> Improvements in BPC version detection, S3 C, and block menus

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Preparing for another release.
> Prepare release 0.96.383

- src/main/webapp/cdn/blockly/core/block_svg.js
- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/frame/framec.jsp
Addresses #1011, #1010, #1014.
> Fixes collapse/expand glitch, menu updates

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
> Adding regex sanity to variable and array names

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/frame/framec.jsp
Large rearrangement of the s3 C block menu/toolbox.  Cleans up block definitions and begins removing some duplicates ahead of the SPIN -> C transition.  More improvements and staging to come.
> s3 C block and toolbox cleanup and improvements

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
Learning that some of the transmogrifier lines that worked well in small programs break in larger ones - commenting them out and falling back to leaving older style blocks in place.
> Commenting out more transmogrifier lines that are not ready

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/editor.js
Adds board-type icon to project description in editor UI.
Removes calls to S3 setups from blocks and adds it to the S3 board type instead.
> UI and S3 C generator improvements

- src/main/java/com/parallax/server/blocklyprop/security/CloudSessionAuthenticationRealm.java
This is the first of many updates to include javadocs in the source.
Also issues a minor refactor to make static class variables uppercase.
> Add Javadoc details

- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectLinkServlet.java
Accidentally routed through the wrong editor (SPIN instead of C) - interestingly did not catch this in testing...
> Correct project editor routing

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/blocklypropclient.js
Initial addition of websocket-based client communication capability
> improve error/loading messages

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/propterm.js
> Fix error with echo trap for non-printable chars

- src/main/webapp/cdn/blockly/generators/propc/variables.js
> Allow bin and hex designators in Array Fill block

- src/main/webapp/WEB-INF/servlet/register/register.jsp
> Fix coppa-restriction date test on registration page

- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
Missed a small part of the a tag that needed to be present to work...
> Add Chrome OS 'client' links for detection and download, part 2

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/clientdownload.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/cdn/editor.js
- src/main/webapp/editor/blocklyc.jsp
Adds a modal that appears if the browser detects that the project has changed and has not been saved for more than 20 minutes.
> Add Chrome OS 'client' links part 4, check for save timer

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
> Bump version to 0.97.419

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
Also, fix for ActivityBot display interp. table, remove old/unused variable setup code, test method for preventing initializers from being added to setup code when blocks are disabled.
> Add device tilt for WX apps on mobile

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
Forgot I needed to clear out the connection handle
> Add Simple WX reconnect block part 2

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/cdn/editor.js
- src/main/webapp/editor/blocklyc.jsp
Addresses #1104, @CarsonGracey give it a try now.
> Improve the save timer warning

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/cdn/editor.js
Also, removes rounding correction that only worked half of the time - opting to simply truncate.
> Improve variable type detection

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/procedures.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
Sets block inputs and outputs to specify and screen for string or number types
Fixes transmogrifier to prevent previously screened projects from being screened again.
> Block type screening and transmogrifier fix

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/WEB-INF/servlet/project/project-link-c.jsp
- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/procedures.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/frame/framec.jsp
- Allows multiple instances of the ColorPal sensor by adding additional init blocks
- Unwraps Open Graph button
- Replaces goudy quotes with unicode ones
- Adds music note value block
- Adds "other" option for serial protocol init block
- Deprecates "PWM start" block, Serial transmit number, Serial receive number
- Changes method for init block detect from looking for library call in c to looking for init block itself
- Enhances Serial transmit and Serial receive
Addresses: #1068, #944, #870, #336
> Block and UI improvements

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/control.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/heb.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
This is so that you can only use the function block inside of the new processor block.
> Set all block top connections to 'Block' type

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
- src/main/webapp/cdn/blocklypropclient.js
Also:
- Begins adding support for multiple serial connections
- Continues adding client detection to UI buttons
- Further deprecates two serial blocks (removes their propc code generators)
> Attempt to fix type checking bug

- src/main/webapp/cdn/propterm.js
Fixed terminal messages from arriving without target serial port.
Also consolidated redundant code.
> [#1129] Fixed terminal messages

- src/main/webapp/cdn/editor.js
Also refactored repeated code into a new function
> Fix empty project warning

- src/main/webapp/cdn/blocklyc.js
> Give terminal focus on opening part 2

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/frame/framec.jsp
- Also, wraps music note block pending discussion of whether education team thinks it's a good idea to implement.
> Set color of deprecated blocks to bright orange

- src/main/webapp/cdn/blockly/generators/propc/variables.js
Until a better solution is built - see #1143
> Disable type-inheriting on variable set block

- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/utils.js
> Revise save before... message, move strings into constants

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/utils.js
Adds callback to bootbox showmessage
> Fixed errors in dialog boxes part 2

- src/main/webapp/cdn/editor.js
Transposed characters in the word 'project'.
> Correct typo in message text

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/project-login-dialog.jsp
- src/main/webapp/cdn/blocklyc.js
> Add MS-Edge/MSIE warning, fix terminal clearing bug

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/sensors.js
- Addresses #1166, #1167, #1126
- Fixes spelling error
> Fixes for multi-device blocks

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
There will probably be a part 3...need to check to see if this glitch affects other blocks.
> Fixes for multi-device blocks part 2

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
This one fixes the errors with the RGB-LEDs.  Will need to apply same repairs to Serial protocol and ColorPal blocks.
> Fixes for multi-device blocks part 3

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
> Fixes for multi-device blocks part 8

- db-updates/0008-update-bp-default-char-col.sql
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/servlet/coppa/privacy-policy.jsp
This patch updates the Parallax privacy policy to incorporate new language.  It also provides an update to the database to ensure that all db objects are using utf8 encoding.
> Patches to privacy policy and db character set

- src/main/webapp/WEB-INF/servlet/index.jsp
Added a <url: /> tag to dynamically locate the image.
> Ginormous image was not referenced correctly.

- src/main/webapp/cdn/editor.js
> Fix broken reference to block canvas

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/editor.js
> Fix broken C 'map' function

- src/main/webapp/WEB-INF/servlet/index.jsp
- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/generators/propc/s3.js
- src/main/webapp/editor/blocklyc.jsp
Several small block fixes
Stages feedback 360 servo blocks
> Block fixes and improvements

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
0.98.422 - Move session management out of the application and to an external system.
> Bumping the build number.

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/PersistenceModule.java
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/db/utils/DataSourceSetup.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Upgraded a pair of Apache Commons database layer packages.
> Build 0.98.423

- src/main/webapp/WEB-INF/servlet/index.jsp
- src/main/webapp/cdn/blockly/generators/propc/base.js
Also changes glyphicon to a unicode char
> Fix advanced math block

- src/main/webapp/cdn/blockly/generators/propc.js
> Attempt to disable keyboard cmds in block workspace in propc projects

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
I still don't like pointers very much.
> Fix WX return IP address block part 4

- src/main/webapp/cdn/blocklyc.js
Added 'Compile...' message which appears before the call to cloud compiler. This shortens user's perception of any compiler delays.
>  Enhance to simplify compile results display.

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
> Add other option to pin menus

- src/main/webapp/WEB-INF/servlet/profile/profile-oauth.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
- src/main/webapp/WEB-INF/servlet/register/register.jsp
- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/editor/blocklyc.jsp
> Add OLED print multiple, restrict chars in screenname

- src/main/java/com/parallax/server/blocklyprop/SessionData.java
- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/UserDao.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/UserDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/security/BlocklyPropSessionDao.java
- src/main/java/com/parallax/server/blocklyprop/services/UserService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SessionServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/UserServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmServlet.java
- src/main/webapp/WEB-INF/web.xml
This PR corrects an issue where the user screen name could become disassociated with the user's projects under very specific conditions.
> Refactor code to correct user id error

- src/main/webapp/editor/blocklyc.jsp
Next time, search the code base for '<<<<' to find a merge conflicts.
> Missed one failed merge block

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/blockly/language/en/_messages.js
- src/main/webapp/editor/blocklyc.jsp
Separates it from the logic_negate block
> Create seperate parentheses block, fix sound init block

- src/main/webapp/cdn/blocklyc.js
First PR made a serious improvement, hopefully this helps.  Was able to bring back the graph after closing, which is a first.  This will hopefully fully reset the data in the graph and its x-axis timestamp.
> Improve graph resetting, part 2

- src/main/webapp/cdn/blocklyc.js
Getting closer.  This fixes the graph, refactors a few functions, but play/pause functionality aren't quite there yet...hopefully in the next one.
> Improve graph resetting part 3

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/servlet/register/register.jsp
Correct issue where date comparison was using a constant '2017'. 
Move alternate email address source drop down to be adjacent to the alternate email address field.
> Register Page Update

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/UserDaoImpl.java
- src/main/resources/documents/confirm/confirmed.textile
Added logging to the code that changes the blocklyprop.user screen name field.
Corrected template error introduced during a merge operation that removes extraneous plus sign characters from the template.
> Add Logging and template correction

- src/main/webapp/cdn/blocklyc.js
Working to account for all possibilities - closing when paused, re-opening, clearing when paused, etc.
> Improve graph play/pause/open/close behavior

- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectServiceImpl.java
Current implementation throws a Null Pointer Exception if the list endpoint is called without parameters. This update provides sane values for parameters that have been omitted.
> Add default parameter values for /rest/project/list endpoint

- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetRequestServlet.java
Correct a couple of issues where we were not verifying project ownership and one where the Cloud Session server was throwing a NullPointer exception that was not trapped correctly.
> Error handling refactoring

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
Reverts parallaxinc/BlocklyProp#1393
> Revert " Apply default values for shared projects when missing "

- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectCreationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectEditorServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectServlet.java
Added more code comments.
Added logging to project-related REST endpoints
Minor code refactoring to clean up redundant code
> 0.100 Documentation

- src/main/webapp/cdn/style-editor.css
> Add CSS position:absolute to blocklySVG canvas

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
> LCD init fix, Hex formatter fixes, Note value typo fix

- src/main/webapp/cdn/style-editor.css
- src/main/webapp/editor/blocklyc.jsp
Still #1410 
Switching to google CDN for now.
> Switch to remote source

- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/style-editor.css
- src/main/webapp/editor/blocklyc.jsp
> Auditioning Encode Sans Semi Condensed Font

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/style-editor.css
- src/main/webapp/editor/blocklyc.jsp
Continuation of #1410 
You can now choose a font from the list below by adding: &font=font+name
Replace font+name with any of the following:
Ubuntu
Lato
Share+Tech
PT+Sans
Heebo
Cabin
ABeeZee
Arimo
Encode+Sans+Semi+Condensed
Exo+2
Open+Sans
More/other choices can be added by request.
> Fix button CSS, options for multiple fonts

- src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
- src/main/webapp/cdn/editor.js
- src/main/webapp/cdn/style.css
- src/main/webapp/editor/blocklyc.jsp
Bug fixes for #1417, #1418, #1419, #1391
> ABdrive init re-order, LCD init fix, serial transmit fix

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/communicate.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
Addresses: #1423, #1422, #1418
> Fix array, multi-core block, and string connection check bugs

- src/main/webapp/cdn/blockly/generators/propc/base.js
- src/main/webapp/cdn/blockly/generators/propc/gpio.js
> Fix servo diff drive bug, add us to pause block

- src/main/webapp/cdn/blockly/generators/propc/communicate.js
Need to find a better way to implement dynamic type checking.
> Fix string type check bug

- src/main/java/com/parallax/server/blocklyprop/utils/OAuthServlet.java
A logging message was exposing an OAuth token into a application the log file.
> Correct log message that exposed a OAuth token.

- src/main/java/com/parallax/server/blocklyprop/config/ServletsModule.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestCompile.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProfile.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestUser.java
- src/main/java/com/parallax/server/blocklyprop/servlets/AuthenticationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/MessageOfTheDayServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PingServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProfileServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectCreationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectEditorServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectLinkServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PublicProfileServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Add consistent log messages to the entry point of all endpoints.
> Add logging to all endpoints

- src/main/webapp/cdn/blockly/generators/propcToolbox.js
A hotfix was applied to the master branch to correct a menu issue in the editor. This commit synch the 101 branch with that hotfix.
> Add Hotfix 1

- src/main/webapp/cdn/blockly/generators/propc.js
- src/main/webapp/cdn/blockly/generators/propc/variables.js
> Change string inits to char arrays

- src/main/webapp/cdn/blockly/generators/propc/base.js
Remove some unnecessary buffering, improved substring extraction function.
> Improve string operations blocks generated propc

- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
The app was not properly trapping some exceptions thrown from the Cloud Session service.
> Add code to catch all Cloud Session service exceptions

- src/main/webapp/cdn/blocklyc.js
Code formatting cleanup (tabs/whitespace), set mutator on graph block properly, provide hooks for improved graph capabilities.
> WIP: graph improvements

- src/main/webapp/cdn/blocklyc.js
While loop seems to be choking
> WIP: More graphing fixes, part 5

- src/main/webapp/cdn/blocklyc.js
> WIP: More graphing fixes - fix overlapping variables

- src/main/webapp/cdn/blocklyc.js
- src/main/webapp/cdn/blocklypropclient.js
Not sure why there is suddenly a race condition, but this should help...
> Move set port list function to the file that uses it

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/editor/blocklyc.jsp
The Beta designation is being removed to indicate that the remaining show-stopper issues have been resolved.
> Remove BETA designation

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/editor-menu.jsp
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/editor/blocklyc.jsp
The application is now stable. Retiring the 'Beta' designation.
> Retiring BETA designation

- pom.xml
Just getting unused things out of the way.
> Remove unneeded dependencies.

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectSharingServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectLinkServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Added debug level logging in the project link code to detect root cause of the error documented in issue #1547. Also refactored code that was not checking method call results before using those results.
Removed commented out dependencies in the project pom file.
> Refactor project link code to add debugging statements.

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProfile.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/security/CloudSessionAuthenticationRealm.java
- src/main/java/com/parallax/server/blocklyprop/services/SecurityService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/AuthenticationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProfileServlet.java
- src/main/resources/logback.xml
- src/main/webapp/WEB-INF/includes/include.jsp
- src/main/webapp/WEB-INF/includes/pageparts/loginform.jsp
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/login.jsp
An update to the cloud-session-java-client introduced an additional EmailNotConfirmed exception. This caused classes that call the interface to fail because they were not handling the added exception correctly.
> Bug fix for error created in cloud-session-java-client

- pom.xml
- src/main/java/com/parallax/server/blocklyprop/config/SetupConfig.java
- src/main/java/com/parallax/server/blocklyprop/converter/ProjectConverter.java
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProfile.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/security/CloudSessionAuthenticationRealm.java
- src/main/java/com/parallax/server/blocklyprop/services/SecurityService.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectSharingServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/SecurityServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/AuthenticationServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProfileServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectLinkServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PublicProfileServlet.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/resources/logback.xml
- src/main/webapp/WEB-INF/includes/include.jsp
- src/main/webapp/WEB-INF/includes/pageparts/loginform.jsp
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile-oauth.jsp
- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
- src/main/webapp/WEB-INF/servlet/register/register.jsp
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/login.jsp
> Release v1.0

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Updating the application version to coincide with the 1.1 branch development.
> Set version to branch 1.1.444.

- .gitignore
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/servlets/RegisterServlet.java
Improve parameter documentation.
Remove redundant code that was introduced during a manual merge process.
Update .gitignore file to exclude the infamous MacOS DS_Store files that tend to pollute a Windows file system.
> Begin process to add MIT license to source files.

- pom.xml
- src/main/resources/shiro.ini
Removed reference to the netbeans repository.
Updated the properties plugin to version 1.0.
> Pom file updates

- src/main/webapp/WEB-INF/servlet/profile/profile.jsp
Allows script to disable it until passwords are validated.
>  Add ID to submit button 

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Bumping the build number in preparation for the release of version 1.1.
> Updating version for release.

- pom.xml
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Version number updated to 1.1.449.
Updated POM file to resolve references to multiple versions of logback package.
> 1.1 - Release

- pom.xml
The configuration block should be within the execution attribute, not outside of it.
> Update pom to correct error in properties package.

- .gitignore
- pom.xml
- src/main/java/com/parallax/server/blocklyprop/db/dao/impl/ProjectDaoImpl.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/rest/RestSharedProject.java
- src/main/java/com/parallax/server/blocklyprop/services/impl/ProjectServiceImpl.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ConfirmServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetRequestServlet.java
- src/main/java/com/parallax/server/blocklyprop/servlets/PasswordResetServlet.java
- src/main/java/com/parallax/server/blocklyprop/utils/RestProjectUtils.java
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/WEB-INF/includes/pageparts/menu.jsp
- src/main/webapp/WEB-INF/servlet/index.jsp
Refactor code in the home page (index.jsp) and the horizontal menu (menu.jsp) to remove HTML warnings, add comments and license text.
> Clean up various warning messages.

- src/main/java/com/parallax/server/blocklyprop/rest/RestProject.java
- src/main/java/com/parallax/server/blocklyprop/servlets/ProjectServlet.java
This is a maintenance update to correct a potential NullPointerException; complete the method documentation; and to refactor a few lines of redundant code that the IDE was complaining about.
These minor changes appear to work as expected on my dev system. Saving a project and Saving As a project both produce the expected results.
> Project REST interface updates

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Preparing for release of version 1.2.448 to production.
> Update application version for 1.2 release

- src/main/webapp/editor/blocklyc.jsp
See notes in [solo-23](https://github.com/parallaxinc/solo/pull/23)
> Make menu option online only

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/my/projects.jsp
Add scripts to the my/project page to support bulk project exports.
Update build number to 1.2.459.
> Add support scripts to my/project page

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
Rolling out updates to support bulk project export.
> Update build number to 1.3.503

- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
- src/main/webapp/editor/blocklyc.jsp
- src/main/webapp/my/projects.jsp
New Feature: Bulk Project downloads.
> Release 1.3.503

- pom.xml
- src/main/resources/com/parallax/server/blocklyprop/internationalization/translations.properties
There is still a reference to the old Log4j package somewhere in the application.
> Add missing logging dependency
